Hotfixes sprint 3
cmpsc-481-s22-m1/PyPiCounter pull request #70
Opened 2022-02-09 23:44 UTC by rachaelharris

# HotFixes Branch 3

## Description
Fixing final hotfixes after the final release

### Type of Change

- [ ] Feature
- [ ] Bug fix
- [x] Documentation

## Contributors

- @rachaelharris 
- @solisa986 

## Reminder

All GitHub Actions should be in a passing state before any pull request is merged.

2022-02-09 23:47 UTC, mariakimheinert requested changes

2022-02-09 23:47 UTC, mariakimheinert commented on README.md
> +will only display the number of the specified construct. For example,
```suggestion
will only return the number of the specified construct. For example,
```

2022-02-09 23:59 UTC, mariakimheinert approved these changes, later dismissed

2022-02-10 00:01 UTC, Michionlion approved these changes, later dismissed

2022-02-10 00:17 UTC, Michionlion approved these changes, later dismissed

2022-02-10 00:18 UTC, mariakimheinert approved these changes, later dismissed
How awesome!

2022-02-10 00:26 UTC, mariakimheinert approved these changes

2022-02-10 00:26 UTC, Michionlion approved these changes

2022-02-10 00:31 UTC, merged